default: &default

  adapter: postgresql
  encoding: unicode
  password: Euco8785
  host: localhost
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: howarts_rails_development

test:
  <<: *default
  database: howarts_rails_test

production:
  <<: *default
  database: howarts_rails_production
  username: howarts_rails
  password: <%= ENV["HOWARTS_RAILS_DATABASE_PASSWORD"] %>